drop table T_REWARD;
drop table T_RESTAURANT;
drop table T_ACCOUNT_BENEFICIARY;
drop table T_ACCOUNT_CREDIT_CARD;
drop table T_ACCOUNT;

create table T_ACCOUNT (ID INT NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT ACCOUNT_PK PRIMARY KEY, NUMBER varchar(9), NAME varchar(50) not null, EMAIL varchar(80), unique(NUMBER));
create table T_ACCOUNT_CREDIT_CARD (ID INT NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT CREDIT_CARD_PK PRIMARY KEY, ACCOUNT_ID integer, NUMBER varchar(16), unique(ACCOUNT_ID, NUMBER));
create table T_ACCOUNT_BENEFICIARY (ID INT NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT BENEFICIARY_PK PRIMARY KEY, ACCOUNT_ID integer, NAME varchar(50), ALLOCATION_PERCENTAGE double not null, SAVINGS double not null, unique(ACCOUNT_ID, NAME));
create table T_RESTAURANT (ID INT NOT NULL GENERATED ALWAYS AS IDENTITY	CONSTRAINT RESTAURANT_PK PRIMARY KEY, MERCHANT_NUMBER varchar(10) not null, NAME varchar(80) not null, BENEFIT_PERCENTAGE double not null, BENEFIT_AVAILABILITY_POLICY varchar(1) not null, unique(MERCHANT_NUMBER));
create table T_REWARD (ID INT NOT NULL GENERATED ALWAYS AS IDENTITY	CONSTRAINT REWARD_PK PRIMARY KEY, REWARD_AMOUNT double not null, REWARD_DATE date not null, ACCOUNT_NUMBER varchar(9) not null, DINING_AMOUNT double not null, DINING_MERCHANT_NUMBER varchar(10) not null, DINING_DATE date not null);

alter table T_ACCOUNT_CREDIT_CARD add constraint FK_ACCOUNT_CREDIT_CARD foreign key (ACCOUNT_ID) references T_ACCOUNT(ID) on delete cascade;
alter table T_ACCOUNT_BENEFICIARY add constraint FK_ACCOUNT_BENEFICIARY foreign key (ACCOUNT_ID) references T_ACCOUNT(ID) on delete cascade;